export default {
login: "NishantReactDeveloper",
id: 19462960,
node_id: "MDQ6VXNlcjE5NDYyOTYw",
avatar_url: "https://avatars.githubusercontent.com/u/19462960?v=4",
gravatar_id: "",
url: "https://api.github.com/users/NishantReactDeveloper",
html_url: "https://github.com/NishantReactDeveloper",
followers_url: "https://api.github.com/users/NishantReactDeveloper/followers",
following_url: "https://api.github.com/users/NishantReactDeveloper/following{/other_user}",
gists_url: "https://api.github.com/users/NishantReactDeveloper/gists{/gist_id}",
starred_url: "https://api.github.com/users/NishantReactDeveloper/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/NishantReactDeveloper/subscriptions",
organizations_url: "https://api.github.com/users/NishantReactDeveloper/orgs",
repos_url: "https://api.github.com/users/NishantReactDeveloper/repos",
events_url: "https://api.github.com/users/NishantReactDeveloper/events{/privacy}",
received_events_url: "https://api.github.com/users/NishantReactDeveloper/received_events",
type: "User",
site_admin: false,
name: "Nishant Kumar",
company: null,
blog: "",
location: null,
email: null,
hireable: null,
bio: "I am a front end web developer",
twitter_username: null,
public_repos: 11,
public_gists: 0,
followers: 0,
following: 0,
created_at: "2016-05-19T05:42:32Z",
updated_at: "2021-06-14T19:45:17Z"
}